default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mijora_challenge_development

test:
  <<: *default
  database: mijora_challenge_test

production:
  <<: *default
  database: mijora_challenge_production
